# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        BOT_TOKEN: NzA5Nzg2NDg4NDgwNzI3MTIy.XsVDCQ.6CffxOo7rlRquLPVo_ztwBc4D0A
        BOT_PREFIX: k!
        HYPIXEL_API_KEY: 3f87c0c1-2273-4a3b-8c8a-91c01bb173ff
        OSU_API_KEY: af6350a5d5f59a0ad0b09b264f85dc74d2e6488c
        MONGO_USER: kayablue
        MONGO_PASSWORD: tgVk48IzbyziKHZ3
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
